HelpDesk/Controllers/ChamadosController.cs
using HelpDesk.Models;
using HelpDesk.Repositorios.Chamados;
using Microsoft.AspNetCore.Mvc;

namespace HelpDesk.Controllers
{
    public class ChamadosController : Controller
    {
        private readonly IChamadoRepositorio _chamadoRepositorio;

        public ChamadosController(IChamadoRepositorio chamadoRepositorio)
        {
            _chamadoRepositorio = chamadoRepositorio; 
        }

        public IActionResult Index()
        {
            List<ChamadoModel> Chamados = _chamadoRepositorio.BuscarChamados(); 
            return View(Chamados);
        }
    }
}

HelpDesk/Controllers/CriarChamadoController.cs
using Microsoft.AspNetCore.Mvc;

namespace HelpDesk.Controllers
{
    public class CriarChamadoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HelpDesk/Controllers/LoginController.cs
using HelpDesk.Data;
using HelpDesk.Helper;
using HelpDesk.Models;
using HelpDesk.Repositorios.Login;
using Microsoft.AspNetCore.Mvc;

namespace HelpDesk.Controllers
{
    public class LoginController : Controller
    {
        private readonly ISessionUser _sessionuser;
        private readonly ILogin _Login;
        public LoginController(ISessionUser sessionUser, ILogin login)
        {
            _sessionuser = sessionUser;
            _Login = login;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult remover()
        {
            _sessionuser.ApagarSessao();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult FazerLogin(LoginModel usuario)
        {
            UsuarioModel usuarioRetornado = _Login.BuscarPorLogin(usuario.Login);

            if (usuarioRetornado != null)
            {
                if(usuarioRetornado.ValidarSenha(usuario.Senha))
                {
                    _sessionuser.CriarSessao(usuarioRetornado);
                    return RedirectToAction("Index", "Home");
                }
                TempData["MensagemErro"] = "Senha incorreta";
                return RedirectToAction("Index");
            }
            TempData["MensagemErro"] = "Usuario incorreto";
            return View("Index", usuario);
        }
    }
}

HelpDesk/Controllers/UsuarioController.cs
using HelpDesk.Helper;
using HelpDesk.Models;
using HelpDesk.Repositorios.Usuario;
using Microsoft.AspNetCore.Mvc;

namespace HelpDesk.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessionUser _sessaoUser;


        public UsuarioController(IUsuarioRepositorio usuarioRepositorio, ISessionUser sessaoUser)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessaoUser = sessaoUser;
        }

        public IActionResult Index()
        {
            List<UsuarioModel> usuarios = _usuarioRepositorio.BuscarTodos(); 
            return View(usuarios);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            UsuarioModel usuario = _usuarioRepositorio.BuscarPorId(id);
            return View(usuario);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            UsuarioModel usuario = _usuarioRepositorio.BuscarPorId(id);
            return View(usuario);
        }

        [HttpPost]
        public IActionResult Criar(UsuarioModel usuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _usuarioRepositorio.CriarUsuario(usuario);
                    _sessaoUser.CriarSessao(usuario);
                    TempData["MensagemSucesso"] = "Usuario Criado com sucesso";
                    return RedirectToAction("Index");

                }
                TempData["MensagemErro"] = "Preencha todos os campos corretamente";
                return View(usuario);
            }
            catch (Exception err)
            {
                TempData["MensagemErro"] = $"Ops, algo Deu errado: {err.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Editar(UsuarioModel usuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _usuarioRepositorio.EditarUsuario(usuario);
                    TempData["MensagemSucesso"] = "Usuario editado com sucesso";
                    return RedirectToAction("Index");
                }
                TempData["MensagemErro"] = "Preencha todos os campos corretamente";
                return View(usuario);
            }
            catch (Exception err)
            {
                TempData["MensagemErro"] = $"Ops, algo deu errado: {err.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool IsApagado = _usuarioRepositorio.ApagarUsuario(id);
                if (IsApagado)
                {
                    TempData["MensagemSucesso"] = "Usuario apagado com suscesso";
                }
                else
                {
                    TempData["MensagemErro"] = "Nao foi possivel apagar esse usuario tente novamente mais tarde";

                }

                return RedirectToAction("Index");
            }
            catch (Exception err)
            {
                TempData["MensagemErro"] = $"Ops, algo deu errado: {err.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

HelpDesk/Views/Shared/_Layout.cshtml
  
@{
    var httpContextAccessor = new HttpContextAccessor();
    var helper = new HelpDesk.Helper.Session(httpContextAccessor);
    var usuario = helper.BuscarSessao();
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HelpDesk.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">



</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom">
            <div class="container-fluid justify-content-end">

                <div class="dropdown">
                    <a href="#"
                       class="d-flex align-items-center gap-2 text-decoration-none dropdown-toggle px-2 py-1
          rounded hover-shadow"
                       data-bs-toggle="dropdown"
                       aria-expanded="false">

                        <div class="rounded-circle bg-primary text-white d-flex align-items-center justify-content-center fw-semibold"
                             style="width:36px; height:36px;">
                            @{
                                string iniciais = "";

                                if (usuario != null && !string.IsNullOrWhiteSpace(usuario.Nome))
                                {
                                    var partes = usuario.Nome
                                    .Trim()
                                    .Split(' ', StringSplitOptions.RemoveEmptyEntries);

                                    if (partes.Length >= 1)
                                        iniciais += partes[0][0];

                                    if (partes.Length >= 2)
                                        iniciais += partes[1][0];
                                }
                            }
                            @iniciais.ToUpper()
                        </div>


                        <span class="fw-semibold text-dark">@usuario.Login</span>
                    </a>


                    <ul class="dropdown-menu dropdown-menu-end shadow">
                        <li><a class="dropdown-item text-danger" asp-action="remover" asp-controller="Login">Sair</a></li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>


    <div class="container-flex">



        <aside class="sidebar bg-light border-end vh-100 p-3" style="position: relative;
    top: -60px;">

            <h5 class="fw-bold mb-4">GLPI 2.0</h5>

           


            @if(usuario.Priviegio == HelpDesk.Enums.PrivilegiosEnum.Tecnico)
            {
                <a asp-action="Index" asp-controller="Home"
                   class="d-flex align-items-center fw-semibold text-muted mb-3 text-decoration-none">
                    <i class="bi bi-arrow-left me-2"></i>
                    Voltar para Menu
                </a>

                <ul class="nav nav-pills flex-column">

                    <li class="nav-item">

                        <a class="nav-link d-flex align-items-center justify-content-between text-dark fw-semibold menu-toggle mb-1"
                           data-bs-toggle="collapse"
                           href="#menuAssistencia"
                           role="button"
                           aria-expanded="false" style="padding: 0px 16px 8px 0;">

                            <div class="d-flex align-items-center">
                                <i class="bi bi-headset me-2 fs-5"></i>
                                Assistência
                            </div>

                            <i class="bi bi-chevron-down transition"></i>
                        </a>

                        <div class="collapse ps-4" id="menuAssistencia">
                            <ul class="nav flex-column mt-2 submenu">

                                <li class="nav-item">
                                    <a class="nav-link d-flex align-items-center fw-semibold text-dark submenu-link" asp-action="Index" asp-controller="Chamados">
                                        <i class="bi bi-exclamation-circle fs-5 me-3"></i>
                                        Chamados
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link d-flex align-items-center fw-semibold text-dark submenu-link" asp-action="Index" asp-controller="CriarChamado">
                                        <i class="bi bi-plus fs-5 me-3"></i>
                                        Criar chamado
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link d-flex align-items-center fw-semibold text-dark submenu-link" asp-action="Index" asp-controller="Usuario">
                                        <i class="bi bi-person fs-5 me-3"></i>
                                        Usuarios
                                    </a>
                                </li>

                            </ul>
                        </div>

                    </li>


                </ul>
            } 
            @if (usuario.Priviegio == HelpDesk.Enums.PrivilegiosEnum.Usuario)
            {
                <a asp-action="Index" asp-controller="Home"
                   class="nav-link d-flex align-items-center fw-semibold text-muted mb-3">
                    <i class="bi bi-arrow-left fs-5 me-3" ></i>
                    Voltar para Menu
                </a>

                <ul class="nav nav-pills flex-column">

                    <li class="nav-item">
                        <a class="nav-link d-flex align-items-center fw-semibold text-dark mb-3" style="padding: 0;" asp-action="Index" asp-controller="Chamados">
                            <i class="bi bi-exclamation-circle fs-5 me-3"></i>
                            Chamados
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link d-flex align-items-center fw-semibold text-dark mb-3"
                           asp-action="Index" asp-controller="CriarChamado" style="padding: 0;">
                            <i class="bi bi-plus fs-5 me-3"></i>
                            Criar chamado
                        </a>
                    </li>

                </ul>

            }
           
        </aside>

       



        <div class="content-wrapper">
            <main class="content">
                @RenderBody()
            </main>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HelpDesk/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HelpDesk.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">



</head>

<body>
        <div class="content-wrapper">
            <main class="content">
                @RenderBody()
            </main>
        </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>